"""
Pytest configuration and shared fixtures for V2 tests
"""
import os
import sys
from pathlib import Path
import pytest
from unittest.mock import Mock, MagicMock

# Add srcv2 to path for imports
srcv2_path = Path(__file__).parent.parent
sys.path.insert(0, str(srcv2_path))


@pytest.fixture
def mock_azure_openai_client():
    """Mock Azure OpenAI client for testing without API calls."""
    mock_client = Mock()
    mock_response = Mock()
    mock_response.choices = [Mock()]
    mock_response.choices[0].message.content = "Sample alt text generated by AI"
    mock_client.chat.completions.create.return_value = mock_response
    return mock_client


@pytest.fixture
def sample_config():
    """Sample configuration for testing."""
    from powerpoint_alttext_v2.config import get_config
    return get_config()


@pytest.fixture
def test_data_dir():
    """Path to test data directory."""
    return Path(__file__).parent / "data"


@pytest.fixture
def sample_pptx_path(test_data_dir):
    """Path to sample PowerPoint file for testing."""
    pptx_path = test_data_dir / "sample.pptx"
    if not pptx_path.exists():
        pytest.skip(f"Sample PPTX file not found: {pptx_path}")
    return pptx_path


@pytest.fixture
def temp_output_dir(tmp_path):
    """Temporary directory for test outputs."""
    output_dir = tmp_path / "outputs"
    output_dir.mkdir(exist_ok=True)
    return output_dir
