"""
Unit tests for PowerPoint Processor core functionality
"""
import pytest
from unittest.mock import Mock, patch, MagicMock
from pathlib import Path

from powerpoint_alttext_v2.core.processor import PowerPointProcessor
from pptx import Presentation
from pptx.util import Inches


class TestPowerPointProcessor:
    """Test PowerPointProcessor class."""
    
    def test_processor_initialization(self, sample_config):
        """Test that processor initializes correctly."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            assert processor.config is not None
            assert processor._seen_titles == {}
    
    def test_processor_with_mock_client(self, sample_config, mock_azure_openai_client):
        """Test processor with mocked Azure OpenAI client."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            processor.client = mock_azure_openai_client
            
            # Test AI alt-text generation
            image_data = "base64encodedimagedata"
            alt_text = processor.generate_alt_text_with_ai(image_data, "test context")
            
            assert alt_text == "Sample alt text generated by AI"
            mock_azure_openai_client.chat.completions.create.assert_called_once()
    
    def test_get_alt_text_from_shape(self, sample_config):
        """Test getting alt text from a shape."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            
            # Create a mock shape
            mock_shape = Mock()
            mock_element = Mock()
            mock_nv = Mock()
            mock_cnvpr = Mock()
            mock_cnvpr.get.return_value = "Test alt text"
            
            mock_nv.find.return_value = mock_cnvpr
            mock_element.tag = "p:sp"
            mock_element.find.return_value = mock_nv
            mock_shape._element = mock_element
            
            alt_text = processor.get_alt_text(mock_shape)
            assert alt_text == "Test alt text"
    
    def test_set_alt_text_on_shape(self, sample_config):
        """Test setting alt text on a shape."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            
            # Create a mock shape
            mock_shape = Mock()
            mock_element = Mock()
            mock_nv = Mock()
            mock_cnvpr = Mock()
            
            mock_nv.find.return_value = mock_cnvpr
            mock_element.tag = "p:sp"
            mock_element.find.return_value = mock_nv
            mock_shape._element = mock_element
            
            result = processor.set_alt_text(mock_shape, "New alt text")
            assert result is True
            mock_cnvpr.set.assert_called_once_with("descr", "New alt text")
    
    def test_is_decorative_auto_shape(self, sample_config):
        """Test decorative shape detection."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            
            # Mock a decorative auto shape
            from pptx.enum.shapes import MSO_SHAPE_TYPE, MSO_AUTO_SHAPE_TYPE
            mock_shape = Mock()
            mock_shape.shape_type = MSO_SHAPE_TYPE.AUTO_SHAPE
            mock_shape.auto_shape_type = MSO_AUTO_SHAPE_TYPE.RECTANGLE
            
            assert processor.is_decorative_auto_shape(mock_shape) is True
    
    def test_is_decorative_container_empty(self, sample_config):
        """Test that empty text boxes are marked as decorative."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            
            # Mock an empty text box
            from pptx.enum.shapes import MSO_SHAPE_TYPE
            mock_shape = Mock()
            mock_shape.shape_type = MSO_SHAPE_TYPE.TEXT_BOX
            mock_shape.text_frame.text = "   "  # Whitespace only
            
            assert processor.is_decorative_container(mock_shape) is True
    
    def test_generate_alt_text_for_text_shape(self, sample_config, mock_azure_openai_client):
        """Test generating alt text for text-only shapes."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            processor.client = mock_azure_openai_client
            
            text_content = "Important bullet point text"
            alt_text = processor.generate_alt_text_for_text_shape(text_content, 1)
            
            assert alt_text == "Sample alt text generated by AI"
            mock_azure_openai_client.chat.completions.create.assert_called_once()
    
    def test_generate_alt_text_for_text_shape_no_client(self, sample_config):
        """Test fallback when AI client is not available."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            processor.client = None
            
            text_content = "This is a very long text that should be truncated in the fallback alt text"
            alt_text = processor.generate_alt_text_for_text_shape(text_content, 1)
            
            assert alt_text.startswith("Text box:")
            assert "This is a very long text that should be truncated" in alt_text
    
    def test_get_existing_slide_title(self, sample_config):
        """Test detecting existing slide titles."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            
            # Mock a slide with a title placeholder
            mock_slide = Mock()
            mock_shape = Mock()
            mock_shape.is_placeholder = True
            mock_shape.placeholder_format.type.name = 'TITLE'
            mock_shape.text_frame.text = "Existing Slide Title"
            
            mock_slide.shapes = [mock_shape]
            
            title = processor.get_existing_slide_title(mock_slide)
            assert title == "Existing Slide Title"
    
    def test_process_shape_with_existing_alt_text(self, sample_config):
        """Test that shapes with existing alt text are skipped."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            
            # Mock shape with existing alt text
            mock_shape = Mock()
            with patch.object(processor, 'get_alt_text', return_value="Existing alt text"):
                result = processor.process_shape(mock_shape, 1, 0)
                
                assert result['processed'] is True
                assert result['alt_text'] == "Existing alt text"


class TestConfigurationHandling:
    """Test configuration handling."""
    
    def test_max_alt_text_length_truncation(self, sample_config, mock_azure_openai_client):
        """Test that alt text is truncated to max length."""
        with patch('powerpoint_alttext_v2.core.processor.get_config', return_value=sample_config):
            processor = PowerPointProcessor()
            processor.client = mock_azure_openai_client
            
            # Mock a very long response
            long_text = "A" * 300
            mock_azure_openai_client.chat.completions.create.return_value.choices[0].message.content = long_text
            
            alt_text = processor.generate_alt_text_with_ai("image_data")
            
            # Should be truncated to max_alt_text_length (180 by default) + "..."
            assert len(alt_text) <= sample_config.processing.max_alt_text_length
